sudo: false

language: node_js

matrix:
  include:
    - node_js: "8"
    - node_js: "9"
      env: COVERALLS=1

# after_success:
#   - if [ "x$COVERALLS" = "x1" ] && npm i coveralls; then
#       npm run cover -- --coverageReporters=text-lcov | coveralls;
#     fi
